//! The tier swatch — every token and every state, resolved, in one text frame
//! per tier.
//!
//! # Why this is a text frame and not a rendered buffer
//!
//! The frame's whole job is to make a tier VISIBLE to a diff. A buffer dump
//! carries symbols and drops style, so the same dump comes out of all four
//! tiers byte-for-byte — which is a real and useful property (it is how the
//! surface proves colour carries no information the glyph does not), and it is
//! exactly the wrong instrument for checking a colour ladder. A frame that
//! names the resolved colour catches a changed hex, a changed index, and a
//! changed slot. A buffer dump catches none of the three.
//!
//! It also keeps this crate where its clean-room classification says it is:
//! resolving a token to a slot number and formatting that as text emits no
//! terminal byte and links no renderer.
//!
//! # What the goldens are for
//!
//! They are this repository's **public mirror of the private tier tables.**
//! CI cannot read the design record — it is in another repository and not a
//! published one — so a test asserting the code against that document directly
//! cannot exist here. The goldens carry the same rows in a form CI can read and
//! a reviewer can eyeball, and the cross-check that they still agree with the
//! record is a script that runs where the record lives. Recorded as a defect
//! against the task that specified the impossible test, not papered over.

use crate::marks::{MARKS, MarkKind, STATES, mark};
use crate::tier::ColorTier;
use crate::{SIGNAL, Token};

/// Render the swatch frame for one tier. Deterministic: the same inputs always
/// produce the same bytes, with no clock, no environment and no ordering that
/// is not the declaration order of the tables.
pub fn frame(tier: ColorTier) -> String {
    let mut out = String::new();
    out.push_str(&format!("SIGNAL SWATCH - tier {}\n", tier.as_str()));
    out.push_str(
        "Generated by `cargo test -p gwk-theme -- swatch`; re-run with BLESS=1 to update.\n\
         This file is the public mirror of the tier tables in the design record.\n\
         Editing it by hand records a decision nobody made.\n\n",
    );

    out.push_str(&format!("TOKENS ({})\n", SIGNAL.len()));
    out.push_str(&format!(
        "  {:<12} {:<8} {:>4}  {:<27} {}\n",
        "token", "value", "256", "tier 16", "this tier"
    ));
    for token in SIGNAL {
        out.push_str(&format!(
            "  {:<12} {:<8} {:>4}  {:<27} {}\n",
            token.name,
            token.value,
            token.index256,
            token.tier16.to_string(),
            token.paint(tier)
        ));
    }

    out.push_str(&format!("\nSTATES ({})\n", STATES.len()));
    out.push_str(&format!(
        "  {:<16} {:<17} {:<6} {:<6} {:<11} {}\n",
        "state", "mark", "glyph", "ascii", "token", "this tier"
    ));
    for state in STATES {
        let (glyph, ascii) = match mark(state.mark) {
            Some(found) => (found.head(), found.ascii),
            // Unreachable: `every_state_binding_resolves_to_a_real_mark_and_a_
            // real_token` pins it. Rendered rather than panicked so a broken
            // binding shows up as a golden diff instead of a crash in a
            // fixture.
            None => ('?', '?'),
        };
        out.push_str(&format!(
            "  {:<16} {:<17} {:<6} {:<6} {:<11} {}\n",
            state.name,
            state.mark,
            glyph,
            ascii,
            state.token,
            paint_of(state.token, tier)
        ));
    }

    out.push_str("\nIDENTITY MARKS (7)\n");
    out.push_str(&format!("  {:<16} {:<6} {}\n", "mark", "glyph", "ascii"));
    for entry in MARKS.iter().filter(|m| m.kind == MarkKind::Identity) {
        out.push_str(&format!(
            "  {:<16} {:<6} {}\n",
            entry.name,
            entry.head(),
            entry.ascii
        ));
    }

    out.push_str("\nCYCLES\n");
    for entry in MARKS.iter().filter(|m| m.glyphs.len() > 1) {
        out.push_str(&format!(
            "  {:<16} {}\n",
            entry.name,
            entry.glyphs.iter().collect::<String>()
        ));
    }

    out.push_str("\nWIDTH RULER - every mark is one cell, so the pipes line up\n  |");
    let mut ruler = String::from("  |");
    for entry in MARKS {
        out.push(entry.head());
        out.push('|');
        ruler.push_str("X|");
    }
    out.push('\n');
    out.push_str(&ruler);
    out.push('\n');
    out
}

fn paint_of(token_name: &str, tier: ColorTier) -> String {
    match SIGNAL.iter().find(|t: &&Token| t.name == token_name) {
        Some(token) => token.paint(tier).to_string(),
        None => "NO SUCH TOKEN".to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn golden_path(tier: ColorTier) -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("goldens")
            .join(format!("swatch-{}.txt", tier.as_str()))
    }

    /// The drift check. Every state's glyph and colour slot, every token's hex
    /// and index and slot, at all four tiers — regenerated and diffed against
    /// the committed frame. A mapping edited in code without the record edited
    /// beside it lands here as a diff a reviewer has to look at.
    #[test]
    fn tier_swatch_frames_match_their_goldens() {
        let bless = std::env::var_os("BLESS").is_some();
        let mut stale: Vec<String> = Vec::new();
        for tier in ColorTier::ALL {
            let rendered = frame(*tier);
            let path = golden_path(*tier);
            if bless {
                if let Some(dir) = path.parent() {
                    std::fs::create_dir_all(dir).expect("create goldens dir");
                }
                std::fs::write(&path, &rendered).expect("write golden");
                continue;
            }
            match std::fs::read_to_string(&path) {
                Ok(committed) if committed == rendered => {}
                Ok(committed) => {
                    let at = committed
                        .lines()
                        .zip(rendered.lines())
                        .position(|(a, b)| a != b);
                    stale.push(match at {
                        Some(line) => format!(
                            "{}: line {} drifted\n  golden:   {:?}\n  rendered: {:?}",
                            path.display(),
                            line + 1,
                            committed.lines().nth(line).unwrap_or_default(),
                            rendered.lines().nth(line).unwrap_or_default(),
                        ),
                        None => format!("{}: length differs", path.display()),
                    });
                }
                Err(why) => stale.push(format!("{}: {why}", path.display())),
            }
        }
        assert!(
            stale.is_empty(),
            "the tier map and its goldens disagree. If the map is right, re-run \
             with BLESS=1 and edit the design record in the same change.\n{}",
            stale.join("\n")
        );
        assert!(
            !bless,
            "BLESS=1 rewrites the goldens; it is not a passing run"
        );
    }

    #[test]
    fn tier_swatch_frames_differ_from_each_other() {
        // The property a buffer dump could not have given us, asserted rather
        // than assumed: four tiers, four distinct frames. If two ever match,
        // the ladder has a rung that does nothing.
        let frames: Vec<String> = ColorTier::ALL.iter().map(|t| frame(*t)).collect();
        for (i, a) in frames.iter().enumerate() {
            for (j, b) in frames.iter().enumerate().skip(i + 1) {
                assert_ne!(
                    a,
                    b,
                    "tiers {} and {} render identically",
                    ColorTier::ALL[i].as_str(),
                    ColorTier::ALL[j].as_str()
                );
            }
        }
    }

    #[test]
    fn tier_swatch_names_every_token_and_every_state() {
        let rendered = frame(ColorTier::Ansi16);
        for token in SIGNAL {
            assert!(rendered.contains(token.name), "token {:?}", token.name);
        }
        for state in STATES {
            assert!(rendered.contains(state.name), "state {:?}", state.name);
        }
        assert!(!rendered.contains("NO SUCH TOKEN"));
    }
}
