// GridWork contract bindings.
// Generated from gwk-domain + gwk-theme by `cargo run -p xtask -- contract`.
// DO NOT EDIT — regenerate instead; CI diffs this file against the source.

// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Who caused an event or issued a command. `kind` is an OPEN bounded string
 *  (e.g. `operator`, `kernel`, `engine`, `liveness_producer`).
 */
export type Actor = Actor_Serialize | Actor_Deserialize;

/**
 *  Who caused an event or issued a command. `kind` is an OPEN bounded string
 *  (e.g. `operator`, `kernel`, `engine`, `liveness_producer`).
 */
export type Actor_Deserialize = {
	kind: string,
	id?: string | null,
};

/**
 *  Who caused an event or issued a command. `kind` is an OPEN bounded string
 *  (e.g. `operator`, `kernel`, `engine`, `liveness_producer`).
 */
export type Actor_Serialize = {
	kind: string,
	id?: string | null,
};

/**  An aggregate instance's identity, unique within its `aggregate_type`. */
export type AggregateId = string;

/**  One engine execution of a task, with its full semantic route snapshot. */
export type Attempt = Attempt_Serialize | Attempt_Deserialize;

export type AttemptId = string;

/**
 *  One engine execution of a task. `unknown` is a first-class terminal — an
 *  attempt whose real outcome cannot be determined is never mapped to `failed`.
 */
export type AttemptState = "queued" | "leased" | "starting" | "running" | "blocked" | "canceling" | "canceled" | "failed" | "unknown" | "succeeded";

/**  One engine execution of a task, with its full semantic route snapshot. */
export type Attempt_Deserialize = {
	id: AttemptId,
	version: number,
	state: AttemptState,
	task_id: TaskId,
	engine: EngineId,
	capability?: string | null,
	role?: string | null,
	/**  The model tier lane (routing), distinct from `engine` (the runtime). */
	model_lane?: string | null,
	permission_profile?: string | null,
	worktree_lease_id?: LeaseId | null,
	base_sha?: string | null,
	budget?: Budget_Deserialize | null,
	result_schema_ref?: string | null,
	provider_session_ref?: string | null,
	runtime_ref?: string | null,
	runtime_started_at?: Timestamp | null,
	exit_code?: number | null,
	provider_terminal_event?: string | null,
	result_valid?: boolean | null,
	evidence_manifest_ref?: string | null,
	gate_result?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  One engine execution of a task, with its full semantic route snapshot. */
export type Attempt_Serialize = {
	id: AttemptId,
	version: number,
	state: AttemptState,
	task_id: TaskId,
	engine: EngineId,
	capability?: string | null,
	role?: string | null,
	/**  The model tier lane (routing), distinct from `engine` (the runtime). */
	model_lane?: string | null,
	permission_profile?: string | null,
	worktree_lease_id?: LeaseId | null,
	base_sha?: string | null,
	budget?: Budget_Serialize | null,
	result_schema_ref?: string | null,
	provider_session_ref?: string | null,
	runtime_ref?: string | null,
	runtime_started_at?: Timestamp | null,
	exit_code?: number | null,
	provider_terminal_event?: string | null,
	result_valid?: boolean | null,
	evidence_manifest_ref?: string | null,
	gate_result?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  Something the operator should look at. `kind` is OPEN. */
export type AttentionItem = AttentionItem_Serialize | AttentionItem_Deserialize;

export type AttentionItemId = string;

/**  Something the operator should look at. `kind` is OPEN. */
export type AttentionItem_Deserialize = {
	id: AttentionItemId,
	kind: string,
	summary: string,
	subject_ref?: string | null,
	raised_by?: Actor_Deserialize | null,
	raised_at: Timestamp,
	resolved_at?: Timestamp | null,
};

/**  Something the operator should look at. `kind` is OPEN. */
export type AttentionItem_Serialize = {
	id: AttentionItemId,
	kind: string,
	summary: string,
	subject_ref?: string | null,
	raised_by?: Actor_Serialize | null,
	raised_at: Timestamp,
	resolved_at?: Timestamp | null,
};

/**  A standing authorization: what `grantee` may do without paging the operator. */
export type AuthorityGrant = AuthorityGrant_Serialize | AuthorityGrant_Deserialize;

export type AuthorityGrantId = string;

/**  A standing authorization: what `grantee` may do without paging the operator. */
export type AuthorityGrant_Deserialize = {
	id: AuthorityGrantId,
	grantee: Actor_Deserialize,
	/**  OPEN action class this grant covers (e.g. `deploy`, `auto_answer`). */
	action_class: string,
	scope?: string | null,
	granted_at: Timestamp,
	expires_at?: Timestamp | null,
	receipt_id?: ReceiptId | null,
};

/**  A standing authorization: what `grantee` may do without paging the operator. */
export type AuthorityGrant_Serialize = {
	id: AuthorityGrantId,
	grantee: Actor_Serialize,
	/**  OPEN action class this grant covers (e.g. `deploy`, `auto_answer`). */
	action_class: string,
	scope?: string | null,
	granted_at: Timestamp,
	expires_at?: Timestamp | null,
	receipt_id?: ReceiptId | null,
};

/**
 *  Resource budget for one attempt. All fields optional: an absent field means
 *  "no cap on this axis", never zero.
 */
export type Budget = Budget_Serialize | Budget_Deserialize;

/**
 *  Spend cursor at checkpoint time (what recovery reconciles against the
 *  authoritative cost ledger).
 */
export type BudgetCursor = BudgetCursor_Serialize | BudgetCursor_Deserialize;

/**
 *  Spend cursor at checkpoint time (what recovery reconciles against the
 *  authoritative cost ledger).
 */
export type BudgetCursor_Deserialize = {
	spent_tokens?: number | null,
	spent_tool_calls?: number | null,
	spent_cost_micros?: string | null,
	window_started_at?: Timestamp | null,
};

/**
 *  Spend cursor at checkpoint time (what recovery reconciles against the
 *  authoritative cost ledger).
 */
export type BudgetCursor_Serialize = {
	spent_tokens?: number | null,
	spent_tool_calls?: number | null,
	spent_cost_micros?: string | null,
	window_started_at?: Timestamp | null,
};

/**
 *  Resource budget for one attempt. All fields optional: an absent field means
 *  "no cap on this axis", never zero.
 */
export type Budget_Deserialize = {
	max_tokens?: number | null,
	max_tool_calls?: number | null,
	max_wall_ms?: number | null,
	max_cost_micros?: string | null,
};

/**
 *  Resource budget for one attempt. All fields optional: an absent field means
 *  "no cap on this axis", never zero.
 */
export type Budget_Serialize = {
	max_tokens?: number | null,
	max_tool_calls?: number | null,
	max_wall_ms?: number | null,
	max_cost_micros?: string | null,
};

/**
 *  A stop/kill command. `outcome` is present iff `state` is
 *  `verification_complete` — written in the same transaction as that terminal
 *  transition (the invariant `gwk-cert` checks and the DDL CHECKs).
 */
export type Command = Command_Serialize | Command_Deserialize;

/**
 *  One issued command. Commands are requests — only the events they cause are
 *  truth. `idempotency_key` is required: reissuing the same key is a no-op.
 */
export type CommandEnvelope = CommandEnvelope_Serialize | CommandEnvelope_Deserialize;

/**
 *  One issued command. Commands are requests — only the events they cause are
 *  truth. `idempotency_key` is required: reissuing the same key is a no-op.
 */
export type CommandEnvelope_Deserialize = {
	command_id: CommandId,
	project_id: ProjectId,
	/**  OPEN bounded string naming the command (e.g. `cancel_attempt`). */
	command_type: string,
	schema_version: number,
	issued_at: Timestamp,
	actor: Actor_Deserialize,
	origin: Origin_Deserialize,
	target_aggregate_type?: string | null,
	target_aggregate_id?: AggregateId | null,
	/**  CAS precondition: the target aggregate's current version. */
	expected_version?: number | null,
	idempotency_key: IdempotencyKey,
	causation_id?: EventId | null,
	correlation_id?: CorrelationId | null,
	payload: JsonValue,
};

/**
 *  One issued command. Commands are requests — only the events they cause are
 *  truth. `idempotency_key` is required: reissuing the same key is a no-op.
 */
export type CommandEnvelope_Serialize = {
	command_id: CommandId,
	project_id: ProjectId,
	/**  OPEN bounded string naming the command (e.g. `cancel_attempt`). */
	command_type: string,
	schema_version: number,
	issued_at: Timestamp,
	actor: Actor_Serialize,
	origin: Origin_Serialize,
	target_aggregate_type?: string | null,
	target_aggregate_id?: AggregateId | null,
	/**  CAS precondition: the target aggregate's current version. */
	expected_version?: number | null,
	idempotency_key: IdempotencyKey,
	causation_id?: EventId | null,
	correlation_id?: CorrelationId | null,
	payload: JsonValue,
};

/**  A command envelope's identity. */
export type CommandId = string;

/**
 *  A stop/kill command's progress spine. The terminal claims only that
 *  verification RAN — the result lives in [`Outcome`], written atomically with
 *  the terminal transition.
 */
export type CommandState = "issued" | "targeted" | "signaled" | "verification_complete";

/**
 *  A stop/kill command. `outcome` is present iff `state` is
 *  `verification_complete` — written in the same transaction as that terminal
 *  transition (the invariant `gwk-cert` checks and the DDL CHECKs).
 */
export type Command_Deserialize = {
	id: CommandId,
	version: number,
	state: CommandState,
	/**  OPEN bounded string (e.g. `stop_attempt`). */
	kind: string,
	target?: string | null,
	actor?: Actor_Deserialize | null,
	idempotency_key?: IdempotencyKey | null,
	outcome?: Outcome | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  A stop/kill command. `outcome` is present iff `state` is
 *  `verification_complete` — written in the same transaction as that terminal
 *  transition (the invariant `gwk-cert` checks and the DDL CHECKs).
 */
export type Command_Serialize = {
	id: CommandId,
	version: number,
	state: CommandState,
	/**  OPEN bounded string (e.g. `stop_attempt`). */
	kind: string,
	target?: string | null,
	actor?: Actor_Serialize | null,
	idempotency_key?: IdempotencyKey | null,
	outcome?: Outcome | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  Correlates every event/command in one logical flow. */
export type CorrelationId = string;

/**
 *  One node in the dispatch tree (who spawned whom). `kind` is OPEN
 *  (e.g. `orchestrator`, `subagent`, `engine`).
 */
export type DispatchNode = DispatchNode_Serialize | DispatchNode_Deserialize;

export type DispatchNodeId = string;

/**
 *  One node in the dispatch tree (who spawned whom). `kind` is OPEN
 *  (e.g. `orchestrator`, `subagent`, `engine`).
 */
export type DispatchNode_Deserialize = {
	id: DispatchNodeId,
	parent_id?: DispatchNodeId | null,
	attempt_id?: AttemptId | null,
	kind: string,
	label?: string | null,
	created_at: Timestamp,
};

/**
 *  One node in the dispatch tree (who spawned whom). `kind` is OPEN
 *  (e.g. `orchestrator`, `subagent`, `engine`).
 */
export type DispatchNode_Serialize = {
	id: DispatchNodeId,
	parent_id?: DispatchNodeId | null,
	attempt_id?: AttemptId | null,
	kind: string,
	label?: string | null,
	created_at: Timestamp,
};

/**
 *  An execution engine, as an OPEN identifier (new engines are additive,
 *  never a breaking enum change).
 */
export type EngineId = string;

/**
 *  One provider-level session under an attempt (an attempt may resume across
 *  several engine sessions).
 */
export type EngineSession = EngineSession_Serialize | EngineSession_Deserialize;

export type EngineSessionId = string;

/**
 *  One provider-level session under an attempt (an attempt may resume across
 *  several engine sessions).
 */
export type EngineSession_Deserialize = {
	id: EngineSessionId,
	attempt_id: AttemptId,
	engine: EngineId,
	provider_session_ref?: string | null,
	started_at: Timestamp,
	ended_at?: Timestamp | null,
};

/**
 *  One provider-level session under an attempt (an attempt may resume across
 *  several engine sessions).
 */
export type EngineSession_Serialize = {
	id: EngineSessionId,
	attempt_id: AttemptId,
	engine: EngineId,
	provider_session_ref?: string | null,
	started_at: Timestamp,
	ended_at?: Timestamp | null,
};

/**
 *  One appended event. Immutable once written; `global_sequence` is assigned by
 *  the kernel append actor in commit order.
 */
export type EventEnvelope = EventEnvelope_Serialize | EventEnvelope_Deserialize;

/**
 *  One appended event. Immutable once written; `global_sequence` is assigned by
 *  the kernel append actor in commit order.
 */
export type EventEnvelope_Deserialize = {
	event_id: EventId,
	project_id: ProjectId,
	/**  OPEN bounded string naming the aggregate family (e.g. `task`, `attempt`). */
	aggregate_type: string,
	aggregate_id: AggregateId,
	/**  Per-aggregate version this event produced: contiguous from 1. */
	aggregate_version: number,
	/**  OPEN bounded string naming the event (e.g. `task_state_changed`). */
	event_type: string,
	schema_version: number,
	global_sequence: string,
	/**  When the change happened in the producing system. */
	occurred_at: Timestamp,
	/**  When the kernel append actor committed it (assigned, never client-set). */
	appended_at: Timestamp,
	actor: Actor_Deserialize,
	origin: Origin_Deserialize,
	causation_id?: EventId | null,
	correlation_id?: CorrelationId | null,
	idempotency_key?: IdempotencyKey | null,
	/**  Bounded inline JSON metadata (≤ [`INLINE_PAYLOAD_MAX_BYTES`] serialized). */
	payload: JsonValue,
	payload_ref?: PayloadRef_Deserialize | null,
};

/**
 *  One appended event. Immutable once written; `global_sequence` is assigned by
 *  the kernel append actor in commit order.
 */
export type EventEnvelope_Serialize = {
	event_id: EventId,
	project_id: ProjectId,
	/**  OPEN bounded string naming the aggregate family (e.g. `task`, `attempt`). */
	aggregate_type: string,
	aggregate_id: AggregateId,
	/**  Per-aggregate version this event produced: contiguous from 1. */
	aggregate_version: number,
	/**  OPEN bounded string naming the event (e.g. `task_state_changed`). */
	event_type: string,
	schema_version: number,
	global_sequence: string,
	/**  When the change happened in the producing system. */
	occurred_at: Timestamp,
	/**  When the kernel append actor committed it (assigned, never client-set). */
	appended_at: Timestamp,
	actor: Actor_Serialize,
	origin: Origin_Serialize,
	causation_id?: EventId | null,
	correlation_id?: CorrelationId | null,
	idempotency_key?: IdempotencyKey | null,
	/**  Bounded inline JSON metadata (≤ [`INLINE_PAYLOAD_MAX_BYTES`] serialized). */
	payload: JsonValue,
	payload_ref?: PayloadRef_Serialize | null,
};

/**  An appended event's identity. */
export type EventId = string;

/**
 *  A pointer to one piece of evidence. `kind` is an OPEN bounded string
 *  (e.g. `transcript`, `diff`, `log`); there is no format column.
 */
export type Evidence = Evidence_Serialize | Evidence_Deserialize;

export type EvidenceId = string;

/**
 *  A pointer to one piece of evidence. `kind` is an OPEN bounded string
 *  (e.g. `transcript`, `diff`, `log`); there is no format column.
 */
export type Evidence_Deserialize = {
	id: EvidenceId,
	kind: string,
	ref: string,
	digest?: string | null,
	byte_size?: string | null,
	created_at: Timestamp,
};

/**
 *  A pointer to one piece of evidence. `kind` is an OPEN bounded string
 *  (e.g. `transcript`, `diff`, `log`); there is no format column.
 */
export type Evidence_Serialize = {
	id: EvidenceId,
	kind: string,
	ref: string,
	digest?: string | null,
	byte_size?: string | null,
	created_at: Timestamp,
};

/**
 *  A verify/review/security/eval/cert checkpoint. `kind` is OPEN; the verdict
 *  set is CLOSED.
 */
export type Gate = Gate_Serialize | Gate_Deserialize;

export type GateId = string;

/**  A gate's verdict — a CLOSED set (the gate `kind` is open). */
export type GateVerdict = "pending" | "pass" | "fail" | "partial";

/**
 *  A verify/review/security/eval/cert checkpoint. `kind` is OPEN; the verdict
 *  set is CLOSED.
 */
export type Gate_Deserialize = {
	id: GateId,
	version: number,
	attempt_id?: AttemptId | null,
	phase_ref?: string | null,
	kind?: string | null,
	verdict: GateVerdict,
	evidence_ref?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  A verify/review/security/eval/cert checkpoint. `kind` is OPEN; the verdict
 *  set is CLOSED.
 */
export type Gate_Serialize = {
	id: GateId,
	version: number,
	attempt_id?: AttemptId | null,
	phase_ref?: string | null,
	kind?: string | null,
	verdict: GateVerdict,
	evidence_ref?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  Caller-chosen key that makes a command or transition retry-stable. */
export type IdempotencyKey = string;

/**
 *  The EXPORT-side shape of JSON metadata payloads. At runtime payloads are
 *  `serde_json::Value` (exact round-trips, arbitrary integer precision); this
 *  type exists so the generated TypeScript says "JSON tree", not `any` — and
 *  it encodes the discipline that a payload NUMBER is IEEE-754 double
 *  territory: anything 64-bit crosses the wire as a decimal string.
 */
export type JsonValue = null | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**
 *  An advisory lease over a scope (worktree, file set, singleton role).
 *  `fence_token` increases on every re-grant of the same scope; storage rejects
 *  writes presenting a stale token.
 */
export type Lease = Lease_Serialize | Lease_Deserialize;

export type LeaseId = string;

/**  Lease sharing mode. */
export type LeaseMode = "exclusive" | "shared";

/**  One held lease, as pinned inside an orchestrator checkpoint. */
export type LeaseSnapshot = LeaseSnapshot_Serialize | LeaseSnapshot_Deserialize;

/**  One held lease, as pinned inside an orchestrator checkpoint. */
export type LeaseSnapshot_Deserialize = {
	lease_id: LeaseId,
	scope?: string | null,
	holder?: string | null,
	expires_at?: Timestamp | null,
};

/**  One held lease, as pinned inside an orchestrator checkpoint. */
export type LeaseSnapshot_Serialize = {
	lease_id: LeaseId,
	scope?: string | null,
	holder?: string | null,
	expires_at?: Timestamp | null,
};

/**
 *  A lease's status set (not one of the four public FSMs — expiry is
 *  time-driven, release is holder-driven).
 */
export type LeaseState = "held" | "released" | "expired";

/**
 *  An advisory lease over a scope (worktree, file set, singleton role).
 *  `fence_token` increases on every re-grant of the same scope; storage rejects
 *  writes presenting a stale token.
 */
export type Lease_Deserialize = {
	id: LeaseId,
	version: number,
	state: LeaseState,
	mode: LeaseMode,
	holder?: string | null,
	scope?: string | null,
	repo?: string | null,
	path?: string | null,
	branch?: string | null,
	base_sha?: string | null,
	fence_token?: string | null,
	heartbeat_at?: Timestamp | null,
	expires_at?: Timestamp | null,
	dirty: boolean,
	unpushed: boolean,
	disposition?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  An advisory lease over a scope (worktree, file set, singleton role).
 *  `fence_token` increases on every re-grant of the same scope; storage rejects
 *  writes presenting a stale token.
 */
export type Lease_Serialize = {
	id: LeaseId,
	version: number,
	state: LeaseState,
	mode: LeaseMode,
	holder?: string | null,
	scope?: string | null,
	repo?: string | null,
	path?: string | null,
	branch?: string | null,
	base_sha?: string | null,
	fence_token?: string | null,
	heartbeat_at?: Timestamp | null,
	expires_at?: Timestamp | null,
	dirty: boolean,
	unpushed: boolean,
	disposition?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  Governed inter-party message. `delivery_refs` maps a delivery channel name
 *  to an opaque per-channel reference (replaces any single-vendor ref column).
 */
export type Message = Message_Serialize | Message_Deserialize;

export type MessageId = string;

/**  Governed inter-party message delivery. */
export type MessageState = "accepted" | "delivered" | "acknowledged" | "applied" | "rejected" | "dead_letter";

/**
 *  Governed inter-party message. `delivery_refs` maps a delivery channel name
 *  to an opaque per-channel reference (replaces any single-vendor ref column).
 */
export type Message_Deserialize = {
	id: MessageId,
	version: number,
	state: MessageState,
	idempotency_key: IdempotencyKey,
	correlation_id?: CorrelationId | null,
	reply_to?: MessageId | null,
	sender?: string | null,
	recipient?: string | null,
	channel?: string | null,
	kind?: string | null,
	payload?: JsonValue | null,
	deadline?: Timestamp | null,
	delivery_attempts: number,
	dead_letter_reason?: string | null,
	delivery_refs?: { [key in string]: string } | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  Governed inter-party message. `delivery_refs` maps a delivery channel name
 *  to an opaque per-channel reference (replaces any single-vendor ref column).
 */
export type Message_Serialize = {
	id: MessageId,
	version: number,
	state: MessageState,
	idempotency_key: IdempotencyKey,
	correlation_id?: CorrelationId | null,
	reply_to?: MessageId | null,
	sender?: string | null,
	recipient?: string | null,
	channel?: string | null,
	kind?: string | null,
	payload?: JsonValue | null,
	deadline?: Timestamp | null,
	delivery_attempts: number,
	dead_letter_reason?: string | null,
	delivery_refs?: { [key in string]: string } | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  One live attempt, as pinned inside an orchestrator checkpoint. */
export type OpenAttemptRef = OpenAttemptRef_Serialize | OpenAttemptRef_Deserialize;

/**  One live attempt, as pinned inside an orchestrator checkpoint. */
export type OpenAttemptRef_Deserialize = {
	attempt_id: AttemptId,
	task_id: TaskId,
	/**
	 *  The attempt's state AT CHECKPOINT TIME, as its wire string. Recovery
	 *  re-reads the live row; this is the crash-time impression, not truth.
	 */
	state: string,
	engine: EngineId,
	worktree_lease_id?: LeaseId | null,
};

/**  One live attempt, as pinned inside an orchestrator checkpoint. */
export type OpenAttemptRef_Serialize = {
	attempt_id: AttemptId,
	task_id: TaskId,
	/**
	 *  The attempt's state AT CHECKPOINT TIME, as its wire string. Recovery
	 *  re-reads the live row; this is the crash-time impression, not truth.
	 */
	state: string,
	engine: EngineId,
	worktree_lease_id?: LeaseId | null,
};

/**
 *  The content of one orchestrator crash-recovery checkpoint (the snapshot
 *  body, not its storage row).
 */
export type OrchestratorCheckpoint = OrchestratorCheckpoint_Serialize | OrchestratorCheckpoint_Deserialize;

/**
 *  The content of one orchestrator crash-recovery checkpoint (the snapshot
 *  body, not its storage row).
 */
export type OrchestratorCheckpoint_Deserialize = {
	orchestrator_id?: string | null,
	/**  Monotonic per-orchestrator checkpoint counter. */
	seq: string,
	native_session_ref?: string | null,
	active_goal?: string | null,
	/**  Opaque reference to the active lifecycle step. */
	active_step_ref?: string | null,
	latest_command_ref?: CommandId | null,
	open_attempts?: OpenAttemptRef_Deserialize[] | null,
	leases?: LeaseSnapshot_Deserialize[] | null,
	pending_approvals?: PendingApproval_Deserialize[] | null,
	budget_cursor?: BudgetCursor_Deserialize | null,
};

/**
 *  The content of one orchestrator crash-recovery checkpoint (the snapshot
 *  body, not its storage row).
 */
export type OrchestratorCheckpoint_Serialize = {
	orchestrator_id?: string | null,
	/**  Monotonic per-orchestrator checkpoint counter. */
	seq: string,
	native_session_ref?: string | null,
	active_goal?: string | null,
	/**  Opaque reference to the active lifecycle step. */
	active_step_ref?: string | null,
	latest_command_ref?: CommandId | null,
	open_attempts?: OpenAttemptRef_Serialize[] | null,
	leases?: LeaseSnapshot_Serialize[] | null,
	pending_approvals?: PendingApproval_Serialize[] | null,
	budget_cursor?: BudgetCursor_Serialize | null,
};

/**
 *  The producing system, opaque to the contract (e.g. a kernel node name, an
 *  adapter). `ref` optionally pins a system-local origin detail.
 */
export type Origin = Origin_Serialize | Origin_Deserialize;

/**
 *  The producing system, opaque to the contract (e.g. a kernel node name, an
 *  adapter). `ref` optionally pins a system-local origin detail.
 */
export type Origin_Deserialize = {
	system: string,
	ref?: string | null,
};

/**
 *  The producing system, opaque to the contract (e.g. a kernel node name, an
 *  adapter). `ref` optionally pins a system-local origin detail.
 */
export type Origin_Serialize = {
	system: string,
	ref?: string | null,
};

/**
 *  A command's verified result — a plain column, NOT an FSM state. Present iff
 *  the command reached `verification_complete`; written in the same transaction.
 */
export type Outcome = "clean" | "partial" | "unknown";

/**  Reference to an out-of-line, content-addressed payload blob. */
export type PayloadRef = PayloadRef_Serialize | PayloadRef_Deserialize;

/**  Reference to an out-of-line, content-addressed payload blob. */
export type PayloadRef_Deserialize = {
	/**
	 *  Content address, `<scheme>:<hex>` (e.g. `sha256:…`). The scheme prefix is
	 *  part of the address; consumers must not assume a single scheme forever.
	 */
	digest: string,
	media_type: string,
	byte_size: string,
	retention_class?: string | null,
	/**  Pinned as evidence: excluded from retention sweeps until unpinned. */
	evidence_pin?: boolean | null,
};

/**  Reference to an out-of-line, content-addressed payload blob. */
export type PayloadRef_Serialize = {
	/**
	 *  Content address, `<scheme>:<hex>` (e.g. `sha256:…`). The scheme prefix is
	 *  part of the address; consumers must not assume a single scheme forever.
	 */
	digest: string,
	media_type: string,
	byte_size: string,
	retention_class?: string | null,
	/**  Pinned as evidence: excluded from retention sweeps until unpinned. */
	evidence_pin?: boolean | null,
};

/**  One decision waiting on the operator, as pinned inside a checkpoint. */
export type PendingApproval = PendingApproval_Serialize | PendingApproval_Deserialize;

/**  One decision waiting on the operator, as pinned inside a checkpoint. */
export type PendingApproval_Deserialize = {
	/**  OPEN bounded string classifying the ask (e.g. `risk_tag`, `design_fork`). */
	kind: string,
	question: string,
	subject_ref?: string | null,
	raised_at: Timestamp,
};

/**  One decision waiting on the operator, as pinned inside a checkpoint. */
export type PendingApproval_Serialize = {
	/**  OPEN bounded string classifying the ask (e.g. `risk_tag`, `design_fork`). */
	kind: string,
	question: string,
	subject_ref?: string | null,
	raised_at: Timestamp,
};

/**  The project (tenant / workspace) an aggregate belongs to. */
export type ProjectId = string;

/**
 *  An attestation that an actor performed an action — the audit row every
 *  auto-answer, state flip, and side effect leaves behind. The D5 blocked-flip
 *  receipt uses `subject_type = "attempt"`, `from`/`to` as the flip edge, and
 *  `observed_basis` naming the liveness evidence.
 */
export type Receipt = Receipt_Serialize | Receipt_Deserialize;

export type ReceiptId = string;

/**
 *  An attestation that an actor performed an action — the audit row every
 *  auto-answer, state flip, and side effect leaves behind. The D5 blocked-flip
 *  receipt uses `subject_type = "attempt"`, `from`/`to` as the flip edge, and
 *  `observed_basis` naming the liveness evidence.
 */
export type Receipt_Deserialize = {
	id: ReceiptId,
	actor: Actor_Deserialize,
	/**  OPEN action attested (e.g. `state_flip`, `auto_answer`, `deploy`). */
	action: string,
	subject_type: string,
	subject_id: string,
	from?: string | null,
	to?: string | null,
	observed_basis?: string | null,
	ts: Timestamp,
};

/**
 *  An attestation that an actor performed an action — the audit row every
 *  auto-answer, state flip, and side effect leaves behind. The D5 blocked-flip
 *  receipt uses `subject_type = "attempt"`, `from`/`to` as the flip edge, and
 *  `observed_basis` naming the liveness evidence.
 */
export type Receipt_Serialize = {
	id: ReceiptId,
	actor: Actor_Serialize,
	/**  OPEN action attested (e.g. `state_flip`, `auto_answer`, `deploy`). */
	action: string,
	subject_type: string,
	subject_id: string,
	from?: string | null,
	to?: string | null,
	observed_basis?: string | null,
	ts: Timestamp,
};

/**
 *  Per-round finding tally appended to an attempt's retry ledger. Actions are
 *  the closed finding taxonomy, snake_case.
 */
export type RoundFindingSummary = {
	total: number,
	auto_fix: number,
	ask_user: number,
	no_op: number,
};

/**  Tracker-visible work item. */
export type Task = Task_Serialize | Task_Deserialize;

export type TaskId = string;

/**  Tracker-visible work item lifecycle (A2A-semantically-verbatim, snake-normalized). */
export type TaskState = "submitted" | "working" | "input_required" | "completed" | "failed" | "canceled";

/**  Tracker-visible work item. */
export type Task_Deserialize = {
	id: TaskId,
	version: number,
	state: TaskState,
	kind?: string | null,
	title?: string | null,
	spec_ref?: string | null,
	project?: string | null,
	priority?: number | null,
	/**  Opaque external-tracker reference (vendor-neutral). */
	tracker_ref?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**  Tracker-visible work item. */
export type Task_Serialize = {
	id: TaskId,
	version: number,
	state: TaskState,
	kind?: string | null,
	title?: string | null,
	spec_ref?: string | null,
	project?: string | null,
	priority?: number | null,
	/**  Opaque external-tracker reference (vendor-neutral). */
	tracker_ref?: string | null,
	created_at: Timestamp,
	updated_at: Timestamp,
};

/**
 *  An RFC 3339 timestamp carried opaquely (the contract pins the format, the
 *  kernel validates it; a plain JSON string on the wire).
 */
export type Timestamp = string;

/**  One named color token. */
export type Token = {
	/**  snake_case token name (CSS uses the kebab-case form). */
	name: string,
	/**  `#RRGGBB` hex color. */
	value: string,
	/**  What the token is FOR — the contract is the role, not the hex. */
	role: string,
};

/**  What `apply` decided, as a tagged wire value. */
export type TransitionResult<S> = { kind: "applied"; state: S; version: number } | { kind: "illegal_edge"; from: S; to: S } | { kind: "stale_version"; actual: number; expected: number } | { kind: "unauthorized_actor"; reason: string };

/**  An isolated working copy a writer attempt runs in. */
export type Worktree = Worktree_Serialize | Worktree_Deserialize;

export type WorktreeId = string;

/**  An isolated working copy a writer attempt runs in. */
export type Worktree_Deserialize = {
	id: WorktreeId,
	repo: string,
	path: string,
	branch: string,
	base_sha?: string | null,
	lease_id?: LeaseId | null,
	dirty: boolean,
	unpushed: boolean,
	created_at: Timestamp,
};

/**  An isolated working copy a writer attempt runs in. */
export type Worktree_Serialize = {
	id: WorktreeId,
	repo: string,
	path: string,
	branch: string,
	base_sha?: string | null,
	lease_id?: LeaseId | null,
	dirty: boolean,
	unpushed: boolean,
	created_at: Timestamp,
};
